---
controller_projects:
- name: demo.datacenter
  organization: Default
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/demo.datacenter.git
